# Generated by Django 4.2.6 on 2023-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionBlog', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='this is a fashion blog', max_length=255),
        ),
    ]
